apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - aks-demo.westus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - aks-demo.westus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer